spring:
  datasource:
    name: test  #数据库名
    url: jdbc:mysql://localhost:3306/test #url
    username: root  #用户名
    password: root  #密码
    #driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动\
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化连接池大小
      initial-size: 5
      # 配置最小连接数
      min-idle: 5
      # 配置最大连接数
      max-active: 20
      # 配置连接等待超时时间
      max-wait: 120000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 120000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 测试连接
      validation-query: SELECT 1
      # 申请连接的时候检测，建议配置为true，不影响性能，并且保证安全
      test-while-idle: true
      # 获取连接时执行检测，建议关闭，影响性能
      test-on-borrow: false
      # 归还连接时执行检测，建议关闭，影响性能
      test-on-return: false
      # 是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      pool-prepared-statements: false
      # 开启poolPreparedStatements后生效
      max-pool-prepared-statement-per-connection-size: 20
      # 配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
      filters: stat,wall,slf4j
      # 打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: ""
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: ""
        # 禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 启用
        enabled: true
mybatis:
  mapper-locations: classpath:mapper/xml/*.xml
#  mapper-locations: classpath*:com/wzb/mapper/**/xml/*Mapper.xml
  type-aliases-package: com.wzb.entity
  configuration:
    # 开启全局缓存配置
    cache-enabled: true
Swagger:
  enable: true
Swagger2:
  configuredFlag=true
server:
  port: 8888
# yml文件配置  redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 2
    #连接超时时间（毫秒）
    timeout: 5000
logging:
  level:
    # 只打印sql，不打印结果集
    com.sanss.mapper: debug

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql